-- Resize embedding column from vector(1536) to vector(768) for Gemini text-embedding-004.
-- Existing embeddings are dropped (they were generated by OpenAI and are incompatible).
DROP INDEX IF EXISTS idx_knowledge_embedding;

ALTER TABLE clinic_knowledge_chunks DROP COLUMN IF EXISTS embedding;
ALTER TABLE clinic_knowledge_chunks ADD COLUMN embedding vector(768);

CREATE INDEX IF NOT EXISTS idx_knowledge_embedding
    ON clinic_knowledge_chunks
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);
